services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=${VITE_PORT}
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_GOOGLE_MAPS_API_KEY=${PUBLIC_GOOGLE_MAPS_API_KEY}
      - PUBLIC_GOOGLE_MAPS_ID=${PUBLIC_GOOGLE_MAPS_ID}
    volumes:
      - ./client:/svelte-app
      - /svelte-app/node_modules


  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"
    volumes:
      - ./server:/server-app
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT:-4000}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_URL=${POSTGRES_URL}
      - GIN_MODE=${GIN_MODE}
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${SERVER_PORT:-4000}/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 2
    #   start_period: 30s
